//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlatTaxPT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlatTaxPT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 659;0,000;0,000;0,000;0,000;0,000;0,000
        ///686;0,001;0,000;0,000;0,000;0,000;0,000
        ///718;0,029;0,009;0,006;0,003;0,000;0,000
        ///739;0,051;0,031;0,018;0,005;0,000;0,000
        ///814;0,057;0,037;0,024;0,018;0,005;0,000
        ///922;0,072;0,053;0,046;0,028;0,022;0,009
        ///1005;0,081;0,062;0,056;0,037;0,032;0,022
        ///1065;0,091;0,071;0,064;0,045;0,036;0,030
        ///1143;0,099;0,086;0,079;0,059;0,053;0,040
        ///1225;0,106;0,094;0,086;0,067;0,060;0,047
        ///1321;0,113;0,108;0,095;0,080;0,067;0,061
        ///1424;0,120;0,114;0,102;0,089;0,075;0,069
        ///1562;0,128;0,1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Acores_Dependente_CasadoDois {
            get {
                return ResourceManager.GetString("Acores_Dependente_CasadoDois", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1310;0,000;0,000;0,000;0,000;0,000;0,000
        ///1414;0,009;0,000;0,000;0,000;0,000;0,000
        ///1455;0,027;0,021;0,000;0,000;0,000;0,000
        ///1639;0,034;0,028;0,014;0,000;0,000;0,000
        ///1956;0,049;0,043;0,031;0,017;0,011;0,000
        ///2079;0,060;0,055;0,041;0,028;0,023;0,017
        ///2213;0,074;0,062;0,056;0,042;0,030;0,024
        ///2314;0,096;0,083;0,070;0,056;0,049;0,043
        ///2479;0,111;0,098;0,084;0,071;0,058;0,051
        ///2561;0,118;0,106;0,100;0,086;0,073;0,067
        ///2663;0,126;0,113;0,107;0,093;0,081;0,074
        ///2929;0,134;0,121;0,115;0,102;0,088;0,082
        ///3247;0,1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Acores_Dependente_CasadoDois_Deficiente {
            get {
                return ResourceManager.GetString("Acores_Dependente_CasadoDois_Deficiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 659;0,000;0,000;0,000;0,000;0,000;0,000
        ///686;0,001;0,000;0,000;0,000;0,000;0,000
        ///708;0,017;0,000;0,000;0,000;0,000;0,000
        ///754;0,024;0,000;0,000;0,000;0,000;0,000
        ///794;0,034;0,007;0,000;0,000;0,000;0,000
        ///836;0,039;0,013;0,007;0,000;0,000;0,000
        ///886;0,046;0,027;0,009;0,000;0,000;0,000
        ///974;0,051;0,033;0,021;0,000;0,000;0,000
        ///1081;0,060;0,040;0,028;0,008;0,000;0,000
        ///1225;0,068;0,051;0,035;0,015;0,001;0,000
        ///1404;0,079;0,066;0,052;0,033;0,019;0,013
        ///1629;0,087;0,074;0,060;0,046;0,034;0,020
        ///1733;0,098;0,085 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Acores_Dependente_CasadoUnico {
            get {
                return ResourceManager.GetString("Acores_Dependente_CasadoUnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1650;0,000;0,000;0,000;0,000;0,000;0,000
        ///1753;0,006;0,000;0,000;0,000;0,000;0,000
        ///1905;0,027;0,008;0,002;0,000;0,000;0,000
        ///1972;0,035;0,023;0,017;0,003;0,000;0,000
        ///2342;0,044;0,039;0,025;0,011;0,000;0,000
        ///2520;0,051;0,046;0,033;0,019;0,005;0,000
        ///2767;0,066;0,061;0,048;0,034;0,028;0,014
        ///2971;0,073;0,068;0,055;0,042;0,036;0,022
        ///3186;0,084;0,079;0,066;0,052;0,046;0,034
        ///3356;0,092;0,090;0,079;0,069;0,066;0,063
        ///3513;0,109;0,108;0,096;0,085;0,082;0,078
        ///3616;0,117;0,116;0,113;0,093;0,089;0,086
        ///3826;0,1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Acores_Dependente_CasadoUnico_Deficiente {
            get {
                return ResourceManager.GetString("Acores_Dependente_CasadoUnico_Deficiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 659;0,000;0,000;0,000;0,000;0,000;0,000
        ///686;0,001;0,000;0,000;0,000;0,000;0,000
        ///718;0,029;0,006;0,000;0,000;0,000;0,000
        ///739;0,051;0,019;0,001;0,000;0,000;0,000
        ///814;0,057;0,033;0,007;0,000;0,000;0,000
        ///922;0,072;0,048;0,025;0,000;0,000;0,000
        ///1005;0,081;0,057;0,040;0,010;0,000;0,000
        ///1065;0,091;0,066;0,048;0,025;0,000;0,000
        ///1143;0,099;0,080;0,062;0,037;0,020;0,002
        ///1225;0,106;0,088;0,070;0,045;0,027;0,009
        ///1321;0,113;0,097;0,078;0,052;0,035;0,017
        ///1424;0,120;0,104;0,086;0,060;0,048;0,030
        ///1562;0,128;0,1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Acores_Dependente_NaoCasado {
            get {
                return ResourceManager.GetString("Acores_Dependente_NaoCasado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1310;0,000;0,000;0,000;0,000;0,000;0,000
        ///1414;0,009;0,000;0,000;0,000;0,000;0,000
        ///1455;0,030;0,005;0,000;0,000;0,000;0,000
        ///1639;0,038;0,019;0,000;0,000;0,000;0,000
        ///1956;0,049;0,035;0,028;0,002;0,000;0,000
        ///2079;0,060;0,046;0,039;0,017;0,009;0,000
        ///2213;0,074;0,053;0,046;0,031;0,017;0,009
        ///2314;0,096;0,074;0,059;0,044;0,029;0,021
        ///2479;0,111;0,089;0,074;0,059;0,045;0,029
        ///2561;0,118;0,104;0,089;0,074;0,052;0,045
        ///2663;0,126;0,112;0,097;0,082;0,067;0,059
        ///2929;0,134;0,119;0,104;0,090;0,082;0,074
        ///3247;0,1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Acores_Dependente_NaoCasado_Deficiente {
            get {
                return ResourceManager.GetString("Acores_Dependente_NaoCasado_Deficiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 659;0,000;0,000;0,000;0,000;0,000;0,000
        ///686;0,001;0,000;0,000;0,000;0,000;0,000
        ///718;0,042;0,013;0,009;0,004;0,000;0,000
        ///739;0,073;0,044;0,026;0,007;0,000;0,000
        ///814;0,082;0,053;0,035;0,026;0,007;0,000
        ///922;0,104;0,076;0,067;0,039;0,032;0,013
        ///1005;0,116;0,089;0,081;0,053;0,045;0,032
        ///1065;0,124;0,098;0,089;0,062;0,049;0,040
        ///1143;0,135;0,117;0,109;0,082;0,073;0,055
        ///1225;0,145;0,128;0,118;0,092;0,083;0,065
        ///1321;0,156;0,148;0,130;0,110;0,093;0,084
        ///1424;0,166;0,158;0,140;0,122;0,103;0,095
        ///1562;0,177;0,1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Continente_Dependente_CasadoDois {
            get {
                return ResourceManager.GetString("Continente_Dependente_CasadoDois", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1310;0,000;0,000;0,000;0,000;0,000;0,000
        ///1414;0,013;0,000;0,000;0,000;0,000;0,000
        ///1455;0,037;0,029;0,000;0,000;0,000;0,000
        ///1639;0,047;0,039;0,020;0,000;0,000;0,000
        ///1956;0,067;0,059;0,042;0,024;0,016;0,000
        ///2079;0,082;0,075;0,056;0,039;0,031;0,023
        ///2213;0,101;0,085;0,077;0,058;0,041;0,033
        ///2314;0,126;0,109;0,092;0,074;0,065;0,057
        ///2479;0,146;0,129;0,111;0,094;0,076;0,067
        ///2561;0,155;0,139;0,131;0,113;0,096;0,088
        ///2663;0,166;0,149;0,141;0,123;0,106;0,098
        ///2929;0,176;0,159;0,151;0,134;0,116;0,108
        ///3247;0,1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Continente_Dependente_CasadoDois_Deficiente {
            get {
                return ResourceManager.GetString("Continente_Dependente_CasadoDois_Deficiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 659;0;0;0;0;0;0
        ///686;0,001;0;0;0;0;0
        ///708;0,024;0;0;0;0;0
        ///754;0,034;0;0;0;0;0
        ///794;0,048;0,01;0;0;0;0
        ///836;0,057;0,019;0,01;0;0;0
        ///886;0,066;0,038;0,013;0;0;0
        ///974;0,074;0,047;0,03;0;0;0
        ///1081;0,083;0,056;0,038;0,011;0;0
        ///1225;0,094;0,07;0,048;0,021;0,002;0
        ///1404;0,109;0,091;0,072;0,044;0,027;0,018
        ///1629;0,119;0,102;0,083;0,064;0,046;0,028
        ///1733;0,134;0,116;0,108;0,079;0,06;0,052
        ///1849;0,143;0,127;0,119;0,092;0,074;0,066
        ///1998;0,153;0,136;0,128;0,102;0,094;0,076
        ///2157;0,163;0,146;0,138;0,111;0,104;0,087
        ///2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Continente_Dependente_CasadoUnico {
            get {
                return ResourceManager.GetString("Continente_Dependente_CasadoUnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1650;0,000;0,000;0,000;0,000;0,000;0,000
        ///1753;0,009;0,000;0,000;0,000;0,000;0,000
        ///1905;0,038;0,011;0,003;0,000;0,000;0,000
        ///1972;0,048;0,031;0,023;0,005;0,000;0,000
        ///2342;0,058;0,051;0,033;0,015;0,000;0,000
        ///2520;0,067;0,061;0,043;0,025;0,007;0,000
        ///2767;0,087;0,080;0,063;0,045;0,037;0,019
        ///2971;0,097;0,090;0,073;0,055;0,047;0,029
        ///3186;0,112;0,105;0,088;0,070;0,062;0,044
        ///3356;0,124;0,121;0,107;0,093;0,089;0,085
        ///3513;0,139;0,138;0,122;0,108;0,104;0,100
        ///3616;0,149;0,148;0,144;0,118;0,114;0,110
        ///3826;0,1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Continente_Dependente_CasadoUnico_Deficiente {
            get {
                return ResourceManager.GetString("Continente_Dependente_CasadoUnico_Deficiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 659;0,000;0,000;0,000;0,000;0,000;0,000
        ///686;0,001;0,000;0,000;0,000;0,000;0,000
        ///718;0,042;0,008;0,000;0,000;0,000;0,000
        ///739;0,073;0,028;0,002;0,000;0,000;0,000
        ///814;0,082;0,046;0,011;0,000;0,000;0,000
        ///922;0,104;0,069;0,036;0,000;0,000;0,000
        ///1005;0,116;0,082;0,058;0,015;0,000;0,000
        ///1065;0,124;0,091;0,067;0,034;0,000;0,000
        ///1143;0,135;0,110;0,086;0,052;0,028;0,003
        ///1225;0,145;0,121;0,096;0,062;0,037;0,013
        ///1321;0,156;0,132;0,108;0,072;0,047;0,023
        ///1424;0,166;0,142;0,117;0,083;0,067;0,041
        ///1562;0,177;0,1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Continente_Dependente_NaoCasado {
            get {
                return ResourceManager.GetString("Continente_Dependente_NaoCasado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1310;0,000;0,000;0,000;0,000;0,000;0,000
        ///1414;0,013;0,000;0,000;0,000;0,000;0,000
        ///1455;0,042;0,007;0,000;0,000;0,000;0,000
        ///1639;0,052;0,027;0,000;0,000;0,000;0,000
        ///1956;0,067;0,048;0,038;0,003;0,000;0,000
        ///2079;0,082;0,063;0,053;0,023;0,013;0,000
        ///2213;0,101;0,073;0,063;0,043;0,023;0,013
        ///2314;0,126;0,097;0,078;0,058;0,038;0,028
        ///2479;0,146;0,117;0,098;0,078;0,059;0,038
        ///2561;0,155;0,137;0,117;0,098;0,068;0,059
        ///2663;0,166;0,147;0,127;0,108;0,088;0,078
        ///2929;0,176;0,157;0,137;0,118;0,108;0,098
        ///3247;0,1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Continente_Dependente_NaoCasado_Deficiente {
            get {
                return ResourceManager.GetString("Continente_Dependente_NaoCasado_Deficiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 659;0,000;0,000;0,000;0,000;0,000;0,000
        ///686;0,001;0,000;0,000;0,000;0,000;0,000
        ///718;0,034;0,010;0,007;0,003;0,000;0,000
        ///739;0,055;0,034;0,020;0,006;0,000;0,000
        ///814;0,069;0,045;0,030;0,022;0,006;0,000
        ///922;0,088;0,064;0,057;0,033;0,027;0,011
        ///1005;0,098;0,075;0,068;0,045;0,038;0,027
        ///1065;0,111;0,088;0,080;0,056;0,044;0,036
        ///1143;0,121;0,105;0,098;0,073;0,065;0,049
        ///1225;0,130;0,115;0,106;0,082;0,074;0,058
        ///1321;0,140;0,132;0,116;0,098;0,083;0,075
        ///1424;0,149;0,141;0,125;0,109;0,092;0,085
        ///1562;0,158;0,1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Madeira_Dependente_CasadoDois {
            get {
                return ResourceManager.GetString("Madeira_Dependente_CasadoDois", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1310;0,000;0,000;0,000;0,000;0,000;0,000
        ///1414;0,012;0,000;0,000;0,000;0,000;0,000
        ///1455;0,033;0,026;0,000;0,000;0,000;0,000
        ///1639;0,042;0,035;0,018;0,000;0,000;0,000
        ///1956;0,063;0,055;0,039;0,022;0,015;0,000
        ///2079;0,077;0,070;0,052;0,037;0,029;0,022
        ///2213;0,095;0,080;0,072;0,054;0,038;0,031
        ///2314;0,118;0,102;0,086;0,069;0,061;0,053
        ///2479;0,137;0,121;0,104;0,088;0,071;0,063
        ///2561;0,145;0,130;0,123;0,106;0,090;0,082
        ///2663;0,155;0,140;0,132;0,115;0,099;0,092
        ///2929;0,165;0,149;0,141;0,126;0,109;0,101
        ///3247;0,1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Madeira_Dependente_CasadoDois_Deficiente {
            get {
                return ResourceManager.GetString("Madeira_Dependente_CasadoDois_Deficiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 659;0,000;0,000;0,000;0,000;0,000;0,000
        ///686;0,001;0,000;0,000;0,000;0,000;0,000
        ///708;0,018;0,000;0,000;0,000;0,000;0,000
        ///754;0,026;0,000;0,000;0,000;0,000;0,000
        ///794;0,037;0,008;0,000;0,000;0,000;0,000
        ///836;0,043;0,014;0,008;0,000;0,000;0,000
        ///886;0,050;0,029;0,010;0,000;0,000;0,000
        ///974;0,058;0,036;0,022;0,000;0,000;0,000
        ///1081;0,065;0,044;0,030;0,009;0,000;0,000
        ///1225;0,072;0,054;0,037;0,016;0,002;0,000
        ///1404;0,098;0,081;0,064;0,039;0,024;0,016
        ///1629;0,107;0,091;0,074;0,057;0,041;0,025
        ///1733;0,120;0,104 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Madeira_Dependente_CasadoUnico {
            get {
                return ResourceManager.GetString("Madeira_Dependente_CasadoUnico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1650;0,000;0,000;0,000;0,000;0,000;0,000
        ///1753;0,008;0,000;0,000;0,000;0,000;0,000
        ///1905;0,034;0,010;0,003;0,000;0,000;0,000
        ///1972;0,045;0,029;0,022;0,005;0,000;0,000
        ///2342;0,054;0,048;0,031;0,014;0,000;0,000
        ///2520;0,063;0,057;0,040;0,023;0,007;0,000
        ///2767;0,081;0,075;0,059;0,042;0,035;0,018
        ///2971;0,091;0,084;0,068;0,052;0,044;0,027
        ///3186;0,109;0,103;0,086;0,068;0,061;0,043
        ///3356;0,121;0,118;0,105;0,091;0,087;0,083
        ///3513;0,136;0,135;0,119;0,106;0,102;0,098
        ///3616;0,146;0,145;0,141;0,115;0,111;0,107
        ///3826;0,1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Madeira_Dependente_CasadoUnico_Deficiente {
            get {
                return ResourceManager.GetString("Madeira_Dependente_CasadoUnico_Deficiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 659;0,000;0,000;0,000;0,000;0,000;0,000
        ///686;0,001;0,000;0,000;0,000;0,000;0,000
        ///718;0,034;0,006;0,000;0,000;0,000;0,000
        ///739;0,055;0,021;0,002;0,000;0,000;0,000
        ///814;0,069;0,039;0,009;0,000;0,000;0,000
        ///922;0,088;0,058;0,030;0,000;0,000;0,000
        ///1005;0,098;0,069;0,049;0,013;0,000;0,000
        ///1065;0,111;0,081;0,060;0,030;0,000;0,000
        ///1143;0,121;0,098;0,077;0,047;0,025;0,003
        ///1225;0,130;0,108;0,086;0,056;0,033;0,012
        ///1321;0,140;0,118;0,097;0,064;0,042;0,021
        ///1424;0,149;0,127;0,105;0,074;0,060;0,037
        ///1562;0,158;0,1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Madeira_Dependente_NaoCasado {
            get {
                return ResourceManager.GetString("Madeira_Dependente_NaoCasado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1310;0,000;0,000;0,000;0,000;0,000;0,000
        ///1414;0,012;0,000;0,000;0,000;0,000;0,000
        ///1455;0,038;0,006;0,000;0,000;0,000;0,000
        ///1639;0,047;0,024;0,000;0,000;0,000;0,000
        ///1956;0,063;0,045;0,036;0,003;0,000;0,000
        ///2079;0,077;0,059;0,050;0,022;0,012;0,000
        ///2213;0,095;0,068;0,059;0,040;0,022;0,012
        ///2314;0,118;0,091;0,073;0,054;0,036;0,026
        ///2479;0,137;0,110;0,092;0,073;0,055;0,036
        ///2561;0,145;0,128;0,110;0,092;0,064;0,055
        ///2663;0,155;0,138;0,119;0,101;0,082;0,073
        ///2929;0,165;0,147;0,128;0,111;0,101;0,092
        ///3247;0,1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Madeira_Dependente_NaoCasado_Deficiente {
            get {
                return ResourceManager.GetString("Madeira_Dependente_NaoCasado_Deficiente", resourceCulture);
            }
        }
    }
}
